# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'ExampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleProject
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'TKUIKit'

end
