# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Review' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Review
  # pod 'TKBaseKit', :git => 'https://github.com/RANSAA/TKBaseKit.git'
  pod 'TKBaseKit', '~> 2.0'
  pod 'YYImage'

end
