# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'PublicBaseTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!


pod 'TKBaseKit', '~> 2.0'



  # Pods for PublicBaseTool

end
