# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FmdbDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FMDB/SQLCipher'


  # Pods for FmdbDemo

  target 'FmdbDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
